kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nginx-build-config
  annotations:
    description: This builds the nginx image from GIT source.
strategy:
  dockerStrategy:
    forcePull: true
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  source:
    type: Git
    git:
      ref: main
      uri: https://github.com/bcgov/des-training.git
    contextDir: docker/nginx
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.template
      buildArgs:
      - name: CODE_VERSION
        value:  1.24.0
  output:
    to:
      kind: ImageStreamTag
      name: nginx:template